export const specialties : string [] = [
  'Addiction Medicine',
  'Addiction Psychiatry',
  'Adolescent Medicine',
  'Adolescent Medicine',
  'Advanced Heart Failure',
  'Aerospace Medicine',
  'Allergy and Immunology',
  'Anatomic Pathology',
  'Anesthesiology',
  'Ankle',
  'Bariatrics',
  'Blood Banking/Transfusion Medicine',
  'Cardiology',
  'Child and Adolescent Psychiatry',
  'Clinical Pathology',
  'Colon and Rectal Surgery',
  'Computed Tomography',
  'Congenital Heart Disease',
  'Cost Savings',
  'Cytopathology',
  'Dermatology',
  'Dermatopathology',
  'Developmental-Behavioral Pediatrics',
  'Diabetic Retinopathy Screening',
  'Efficiency',
  'Electrophysiology',
  'Emergency Medicine',
  'Endocrinology',
  'Epilepsy',
  'FTE Reduction',
  'Family Medicine',
  'Female Pelvic Medicine and Reconstructive Surgery',
  'Forensic Pathology',
  'Gastroenterology',
  'General Dermatology',
  'General Family Medicine',
  'General Internal Medicine',
  'General Ophthalmology',
  'Geriatric Medicine',
  'Geriatric Medicine',
  'Geriatric Psychiatry',
  'Gynecologic Oncology',
  'Hand/Wrist/Elbow',
  'Hematology',
  'Hematopathology',
  'Hip',
  'Hospice and Palliative Medicine',
  'Hospice and Palliative Medicine',
  'Infectious Disease',
  'Internal Medicine',
  'Interventional Cardiology',
  'Interventional Radiology',
  'Intra-Operative Monitoring',
  'Intra-Operative Processes',
  'Knee',
  'Magnetic Resonance Imaging',
  'Maternal-Fetal Medicine',
  'Medical Genetics and Genomics',
  'Medical Oncology',
  'Medical Toxicology',
  'Molecular Genetic Pathology',
  'Neonatal weight gain',
  'Neonatal-Perinatal Medicine',
  'Nephrology',
  'Neurocritical Care',
  'Neurodevelopmental Disabilities',
  'Neurological Surgery',
  'Neurology',
  'Neuroradiology',
  'Neurotology',
  'Nuclear Medicine',
  'Obstetrics and Gynecology',
  'Occupational Medicine',
  'Ophthalmology Screening Rates',
  'Ophthalmology',
  'Orthopedic Sports Medicine',
  'Orthopedic Surgery',
  'Otolaryngology',
  'Pain Medicine',
  'Pain Medicine',
  'Pathology',
  'Pediatric Anesthesiology',
  'Pediatric Cardiology',
  'Pediatric Critical Care Medicine',
  'Pediatric Dermatology',
  'Pediatric Emergency Medicine',
  'Pediatric Endocrinology',
  'Pediatric Hematology-Oncology',
  'Pediatric Hospital Medicine',
  'Pediatric Infectious Disease',
  'Pediatric Nephrology',
  'Pediatric Ophthalmology',
  'Pediatric Orthopedics',
  'Pediatric Otolaryngology',
  'Pediatric Pulmonology',
  'Pediatric Rheumatology',
  'Pediatric Transplant Hepatology',
  'Pediatric Urology',
  'Pediatrics',
  'Physical Medicine and Rehabilitation',
  'Plastic Surgery',
  'Podiatry',
  'Post-Operative Length of Stay',
  'Post-Operative Processes',
  'Pre-Operative Processes',
  'Preventive Medicine',
  'Procedural No Show Rates',
  'Psychiatry',
  'Public Health and General Preventive Medicine',
  'Pulmonology',
  'Radiation Oncology',
  'Radiology',
  'Reproductive Endocrinology and Infertility',
  'Rheumatology',
  'Shoulder',
  'Sleep Medicine',
  'Sleep Medicine',
  'Spine',
  'Sports Medicine',
  'Thoracic Surgery',
  'Transplant Cardiology',
  'Transplant Hepatology',
  'Transplant Surgery',
  'Ultrasound',
  'Undersea and Hyperbaric Medicine',
  'Urology',
  'Vascular Surgery',
  'XRay',
'General Surgery'
]